# Generated by Django 3.2.9 on 2024-06-05 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpreadBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=255)),
                ('settings', models.JSONField()),
                ('buy_status', models.BooleanField(default=False)),
                ('sell_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spread.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadBotTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10)),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('fee', models.FloatField()),
                ('profit', models.FloatField()),
                ('condition', models.CharField(default='M', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spread.spreadbot')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spread.exchange')),
            ],
        ),
    ]
