# Generated by Django 3.2.9 on 2024-06-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeapi',
            name='kyc',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
