# Generated by Django 3.2.9 on 2024-06-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0002_exchangeapi_kyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadbot',
            name='settings',
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='average_correction_minutes',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='average_correction_rate',
            field=models.FloatField(default=0.02),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='average_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='budget',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='last_buy_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='last_sell_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='last_sell_order_date_raw',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='max_size',
            field=models.FloatField(default=300),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='profit_rate',
            field=models.FloatField(default=0.005),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='sellable_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='spread_rate',
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name='spreadbot',
            name='take_profit_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
