# Generated by Django 3.2.9 on 2024-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread', '0003_auto_20240605_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadbot',
            name='average_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='spreadbot',
            name='sellable_quantity',
            field=models.FloatField(default=0),
        ),
    ]
